apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsapp-bot-api
  namespace: prod
  labels:
    app: whatsapp-bot-api
spec:
  selector:
    matchLabels:
      app: whatsapp-bot-api
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: whatsapp-bot-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: whatsapp-bot-api
          image: ghcr.io/champalab/whatsapp-bot-api:115268d9f6631738d615cbbd6145920de71a8595
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
              memory: 100Mi
            limits:
              cpu: 2000m
              memory: 2048Mi
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: whatsapp-bot-api-config
            # - secretRef:
            #     name: database-easy-pos
            # - secretRef:
            #     name: jwt-secret
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: whatsapp-bot-api
              mountPath: /app/logs
              subPath: whatsapp-bot-api/logs
            - name: whatsapp-bot-api
              mountPath: /app/uploads
              subPath: whatsapp-bot-api/uploads
            - name: whatsapp-bot-api
              mountPath: /app/whatsapp-sessions
              subPath: whatsapp-bot-api/whatsapp-sessions
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Bangkok
        - name: whatsapp-bot-api
          nfs:
            path: /mnt/gfs
            server: gfs-01
      restartPolicy: Always
