name: Prod environment CI and CD

on:
    push:
        branches: ['main']

jobs:
    # ==============
    # CI task
    # ==============
    build-and-push-docker-image:
        name: Build Docker image and push to repositories
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: Setup SHA
              run: echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
            - name: Login ghcr.io
              uses: docker/login-action@v2.1.0
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.WORKFLOW_TOKEN }}
                  logout: true
            - name: Pull the latest Docker image
              run: docker pull ghcr.io/champalab/easy-pos-api:latest || true
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag ghcr.io/champalab/easy-pos-api:${{ env.GITHUB_SHA }} --tag ghcr.io/champalab/easy-pos-api:latest
            - name: Push the Docker image
              run: docker push ghcr.io/champalab/easy-pos-api:${{ env.GITHUB_SHA }}
            - name: Push the Docker image latest
              run: docker push ghcr.io/champalab/easy-pos-api:latest

    # ==============
    # CD PORD task
    # ==============
    gitops-prod-versioning:
        runs-on: ubuntu-latest
        needs: [build-and-push-docker-image]
        steps:
            - name: checkout
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.WORKFLOW_TOKEN }}

            - name: config git
              run: |
                  git --version
                  git config user.name "robot"
                  git config user.email "root@champalab.com"
            - name: change image tag to deploy prod
              run: |
                  sed "s|image: ghcr\.io/champalab/easy-pos-api:[^ ]*|image: ghcr.io/champalab/easy-pos-api:${GITHUB_SHA}|" k8s/prod/deployment.yaml > tmp_deployment.yaml
                  mv tmp_deployment.yaml k8s/prod/deployment.yaml
                  git add k8s/prod/deployment.yaml
                  git commit -m "[skip actions] 🤖 change prod docker image version to ${GITHUB_SHA}"
                  git pull origin main --rebase
                  git push
